# ----------------------------------------------------------------- #
# ----------------------------------------------------------------- #


BaseParserError = (IndexError, TypeError, ValueError, AttributeError)


class BaseImportError(ImportError):
    """Base class for all sources generated by ImportError."""

    pass


# -------------------------------------------------- #
# -------------------------------------------------- #


class ModuleNotLoadedError(BaseImportError):
    """There was a problem loading the module."""

    pass


# -------------------------------------------------- #
# -------------------------------------------------- #


class ClassNotFoundError(BaseImportError):
    """There was a problem found the class."""

    pass


# ----------------------------------------------------------------- #
# ----------------------------------------------------------------- #
